apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway
spec:
  type: NodePort
  ports:
    - name: port-8080
      port: 8080
      targetPort: 8080
      nodePort: 30020
  selector:
    app: fleetman-api-gateway
