apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-simulator
spec:
  ports:
    - name: port-8080
      port: 8080
      targetPort: 8080
  selector:
    app: fleetman-position-simulator