apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
  ports:
    - name: port-8161
      port: 8161
      targetPort: 8161
    - name: port-61616
      port: 61616
      targetPort: 61616
  selector:
    app: fleetman-queue
